[package]
name = "portal-web"
edition.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
rust-embed.workspace = true
portal-config.workspace = true
portal-feature.workspace = true
portal-model.workspace = true
serde.workspace = true
toml_edit.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tokio.workspace = true
