import {
  Activity,
  Bell,
  Calendar,
  Clock,
  Cloud,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Film,
  Gauge,
  HardDrive,
  Heart,
  House,
  Lightbulb,
  Lock,
  type LucideIcon,
  Music,
  Play,
  Power,
  RefreshCw,
  RotateCcw,
  Router,
  Server,
  Shield,
  Square,
  Thermometer,
  Trash2,
  Upload,
  Users,
  Wifi,
  Zap,
} from "lucide-react";

export const BLOCK_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  cloud: Cloud,
  cpu: Cpu,
  database: Database,
  download: Download,
  "external-link": ExternalLink,
  film: Film,
  gauge: Gauge,
  "hard-drive": HardDrive,
  heart: Heart,
  house: House,
  lightbulb: Lightbulb,
  lock: Lock,
  music: Music,
  play: Play,
  power: Power,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  router: Router,
  server: Server,
  shield: Shield,
  square: Square,
  thermometer: Thermometer,
  "trash-2": Trash2,
  upload: Upload,
  users: Users,
  wifi: Wifi,
  zap: Zap,
};

