export const routes = {
  home: "/",
  login: "/login/",
  fatal: "/fatal/",
  service: (id: string) => `/service/?id=${encodeURIComponent(id)}`,
  adminServices: "/admin/services/",
  adminLayout: "/admin/layout/",
  layoutWidget: (id: string) => `/admin/layout/widgets/?widget=${encodeURIComponent(id)}`,
  adminLibrary: "/admin/layout/widgets/",
  newWidget: (template: string | null, back: "layout" | "library" = "library") =>
    `/admin/layout/widgets/new/?${new URLSearchParams({ ...(template === null ? {} : { template }), back }).toString()}`,
  editWidget: (id: string, back: "layout" | "library" = "library", place: string | null = null) =>
    `/admin/layout/widgets/edit/?${new URLSearchParams({ id, back, ...(place === null ? {} : { place }) }).toString()}`,
  adminNetwork: "/admin/network/",
  adminModules: "/admin/modules/",
  adminProxy: "/admin/proxy/",
  adminDns: "/admin/dns/",
  adminAutomations: "/admin/automations/",
  newAutomation: "/admin/automations/new/",
  editAutomation: (id: string) => `/admin/automations/edit/?id=${encodeURIComponent(id)}`,
  adminWebhooks: "/admin/webhooks/",
  adminUsers: "/admin/users/",
  adminWorkflows: "/admin/workflows/",
  newWorkflow: "/admin/workflows/new/",
  workflow: (id: string) => `/admin/workflows/${encodeURIComponent(id)}/`,
  workflowEdit: (id: string) => `/admin/workflows/${encodeURIComponent(id)}/edit/`,
  workflowHistory: (id: string) => `/admin/workflows/${encodeURIComponent(id)}/history/`,
  workflowRun: (id: string, run: string) => `/admin/workflows/${encodeURIComponent(id)}/history/${encodeURIComponent(run)}/`,
  adminNotifications: "/admin/notifications/",
  adminScripts: "/admin/scripts/",
  script: (path: string) => `/admin/scripts/?path=${encodeURIComponent(path)}`,
  adminRuns: "/admin/runs/",
  run: (id: string) => `/admin/runs/?run=${encodeURIComponent(id)}`,
  adminPermissions: "/admin/permissions/",
  newWebhook: "/admin/webhooks/new/",
  editWebhook: (id: string) => `/admin/webhooks/edit/?id=${encodeURIComponent(id)}`,
  webhookDetails: (id: string) => `/admin/webhooks/details/?id=${encodeURIComponent(id)}`,
  newService: "/admin/services/new/",
  editService: (id: string) => `/admin/services/edit/?id=${encodeURIComponent(id)}`,
} as const;

export const api = {
  session: "/api/session",
  services: "/api/services",
  service: (id: string) => `/api/services/${encodeURIComponent(id)}`,
  serviceProbe: (id: string) => `/api/services/${encodeURIComponent(id)}/probe`,
  serviceHistory: (id: string, range: string) =>
    `/api/services/${encodeURIComponent(id)}/history?range=${encodeURIComponent(range)}`,
  network: "/api/network",
  restartPortal: "/api/portal/restart",
  portalFailure: "/api/portal/failure",
  health: "/health",
  dashboard: "/api/dashboard",
  layout: "/api/dashboard?all=true",
  library: "/api/dashboard/library",
  libraryWidget: (id: string) => `/api/dashboard/library/${encodeURIComponent(id)}`,
  environment: "/api/environment",
  widget: (id: string) => `/api/widgets/${encodeURIComponent(id)}/data`,
  widgetAction: (id: string, action: string) => `/api/widgets/${encodeURIComponent(id)}/actions/${encodeURIComponent(action)}`,
  widgetPreview: "/api/widgets/preview",
  icon: (id: string) => `/api/icons/${encodeURIComponent(id)}`,
  iconPreview: "/api/icon-preview",
  publicPortal: "/api/public/portal",
  publicWidget: (id: string) => `/api/public/widgets/${encodeURIComponent(id)}/data`,
  publicIcon: (id: string) => `/api/public/icons/${encodeURIComponent(id)}`,
  proxy: "/api/proxy",
  dns: "/api/dns",
  modules: "/api/modules",
  module: (name: string) => `/api/modules/${encodeURIComponent(name)}`,
  users: "/api/users",
  user: (name: string) => `/api/users/${encodeURIComponent(name)}`,
  userPassword: (name: string) => `/api/users/${encodeURIComponent(name)}/password`,
  userGroup: (name: string) => `/api/users/${encodeURIComponent(name)}/group`,
  groups: "/api/groups",
  group: (name: string) => `/api/groups/${encodeURIComponent(name)}`,
  webhookRun: (id: string) => `/api/webhooks/${encodeURIComponent(id)}/run`,
  proxyApply: "/api/proxy/apply",
  proxyContinue: (to: string) => `/api/proxy/continue?to=${encodeURIComponent(to)}`,
  proxyRootCertificate: "/api/proxy/root-certificate",
  caddySource: "/api/proxy/caddy",
  caddyDownload: "/api/proxy/caddy/download",
  caddyStart: "/api/proxy/caddy/start",
  caddyStop: "/api/proxy/caddy/stop",
  automations: "/api/automations",
  automation: (id: string) => `/api/automations/${encodeURIComponent(id)}`,
  automationRun: (id: string) => `/api/automations/${encodeURIComponent(id)}/run`,
  automationRuns: (filter: { automation?: string | null; webhook?: string | null; workflow?: string | null; text?: string | null; before?: string | null; limit?: number | null }) => {
    const query = new URLSearchParams();
    for (const [name, value] of Object.entries(filter)) {
      if (value) {
        query.set(name, String(value));
      }
    }
    const text = query.toString();
    return text === "" ? "/api/automations/runs" : `/api/automations/runs?${text}`;
  },
  automationRunItem: (id: string) => `/api/automations/runs/${encodeURIComponent(id)}`,
  automationRunStop: (id: string) => `/api/automations/runs/${encodeURIComponent(id)}/stop`,
  automationCatalogue: "/api/automations/catalogue",
  automationScripts: "/api/automations/scripts",
  automationSchedule: (cron: string) => `/api/automations/schedule?cron=${encodeURIComponent(cron)}`,
  webhooks: "/api/webhooks",
  webhook: (id: string) => `/api/webhooks/${encodeURIComponent(id)}`,
  webhookToken: (id: string) => `/api/webhooks/${encodeURIComponent(id)}/token`,
  workflows: "/api/workflows",
  workflow: (id: string) => `/api/workflows/${encodeURIComponent(id)}`,
  workflowRun: (id: string) => `/api/workflows/${encodeURIComponent(id)}/run`,
  workflowCatalogue: "/api/workflows/catalogue",
  workflowPortal: "/api/workflows/portal",
  transformPreview: "/api/workflows/transform-preview",
  secrets: "/api/secrets",
  notifications: "/api/notifications",
  notificationChannel: (name: string) => `/api/notifications/channels/${encodeURIComponent(name)}`,
  notificationTest: "/api/notifications/test",
  scripts: "/api/scripts",
  scriptFile: (path?: string) => (path === undefined ? "/api/scripts/file" : `/api/scripts/file?path=${encodeURIComponent(path)}`),
  scriptFolder: (name?: string) => (name === undefined ? "/api/scripts/folder" : `/api/scripts/folder?name=${encodeURIComponent(name)}`),
  scriptMove: "/api/scripts/move",
  permissions: "/api/permissions",
  permissionsRequest: "/api/permissions/request",
} as const;

export const MODULE_PAGES = {
  proxy: routes.adminProxy,
  dns: routes.adminDns,
  automations: routes.adminAutomations,
  webhooks: routes.adminWebhooks,
  users: routes.adminUsers,
  workflows: routes.adminWorkflows,
  notifications: routes.adminNotifications,
} as const;

export const STATUS_REFRESH_MILLISECONDS = 10_000;
