[package]
name = "portal-widgets"
edition.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
portal-config.workspace = true
portal-feature.workspace = true
portal-model.workspace = true
portal-widget.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
toml_edit.workspace = true

[dev-dependencies]
portal-testing.workspace = true
tempfile.workspace = true
tokio.workspace = true
tower.workspace = true
http-body-util.workspace = true
